# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_flags_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setToolTip("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.update_flags_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_flags_button.setGeometry(QtCore.QRect(290, 130, 301, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_flags_button.sizePolicy().hasHeightForWidth())
        self.update_flags_button.setSizePolicy(sizePolicy)
        self.update_flags_button.setObjectName("update_flags_button")
        self.user_list = QtWidgets.QListWidget(self.centralwidget)
        self.user_list.setGeometry(QtCore.QRect(10, 10, 271, 481))
        self.user_list.setObjectName("user_list")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(10, 500, 581, 91))
        self.back_button.setObjectName("back_button")
        self.is_student_box = QtWidgets.QCheckBox(self.centralwidget)
        self.is_student_box.setGeometry(QtCore.QRect(290, 10, 150, 23))
        self.is_student_box.setObjectName("is_student_box")
        self.is_teacher_box = QtWidgets.QCheckBox(self.centralwidget)
        self.is_teacher_box.setGeometry(QtCore.QRect(290, 40, 150, 23))
        self.is_teacher_box.setObjectName("is_teacher_box")
        self.is_principal_box = QtWidgets.QCheckBox(self.centralwidget)
        self.is_principal_box.setGeometry(QtCore.QRect(290, 70, 150, 23))
        self.is_principal_box.setObjectName("is_principal_box")
        self.is_admin_box = QtWidgets.QCheckBox(self.centralwidget)
        self.is_admin_box.setGeometry(QtCore.QRect(290, 100, 150, 23))
        self.is_admin_box.setObjectName("is_admin_box")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление правами"))
        self.update_flags_button.setText(_translate("MainWindow", "Обновить флаги"))
        self.back_button.setText(_translate("MainWindow", "Назад"))
        self.is_student_box.setText(_translate("MainWindow", "ученик"))
        self.is_teacher_box.setText(_translate("MainWindow", "преподаватель"))
        self.is_principal_box.setText(_translate("MainWindow", "директор"))
        self.is_admin_box.setText(_translate("MainWindow", "администратор"))
